# -*- coding: utf-8 -*-
"""TEST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19pY2yqxOxmRdOx8nupW8K0Ng5CTt0Bgs
"""

df = " hello this for testing"

print (df)